apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-frontend
  namespace: sre-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-frontend
  template:
    metadata:
      labels:
        app: sre-frontend
    spec:
      containers:
        - name: frontend
          image: kotidevops/kt-frontend:v6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: sre-platform
spec:
  selector:
    app: sre-frontend
  ports:
    - port: 80
      targetPort: 80
# Ingress rules have moved to k8s/ingress.yaml
