apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: sre-frontend
    {{- include "sre-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: sre-frontend
  template:
    metadata:
      labels:
        app: sre-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
