apiVersion: v1
kind: Secret
metadata:
  name: sre-platform-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sre-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  PGPASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  GRAFANA_PASSWORD: {{ .Values.secrets.grafanaPassword | quote }}
  POSTGRES_EXPORTER_DSN: "postgresql://{{ .Values.postgres.user }}:{{ .Values.secrets.postgresPassword }}@localhost:5432/{{ .Values.postgres.database }}?sslmode=disable"
