apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  slack-webhook-url: {{ .Values.alertmanager.slackWebhookUrl | quote }}
