apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  GRAFANA_PASSWORD: {{ .Values.grafana.adminPassword | quote }}
